Administrateur:
    type: entity
    table: administrateur
    id:
        idAdministrateur:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: id_administrateur
            generator:
                strategy: IDENTITY
    fields:
        prenom:
            type: string
            nullable: false
            length: 45
            fixed: false
            comment: ''
        nom:
            type: string
            nullable: false
            length: 45
            fixed: false
            comment: ''
        email:
            type: string
            nullable: false
            length: 45
            fixed: false
            comment: ''
        estSuperAdmin:
            type: boolean
            nullable: false
            comment: ''
            column: est_super_admin
        mdp:
            type: string
            nullable: true
            length: 32
            fixed: false
            comment: ''
    lifecycleCallbacks: {  }
