Etat:
    type: entity
    table: etat
    id:
        idEtat:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: id_etat
            generator:
                strategy: IDENTITY
    fields:
        nom:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
    lifecycleCallbacks: {  }
