Postionmodule:
    type: entity
    table: postionmodule
    indexes:
        fk_PostionModule_BlocModule1_idx:
            columns:
                - bloc_module_id
    id:
        idPosition:
            type: integer
            nullable: false
            unsigned: false
            id: true
            column: id_position
            generator:
                strategy: IDENTITY
    fields:
        positionVerticale:
            type: integer
            nullable: false
            unsigned: false
            column: position_verticale
        largeurModule:
            type: integer
            nullable: false
            unsigned: false
            column: largeur_module
        action:
            type: string
            nullable: false
            length: 45
            fixed: false
        publie:
            type: boolean
            nullable: false
    manyToOne:
        blocModule:
            targetEntity: Blocmodule
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                bloc_module_id:
                    referencedColumnName: id_bloc_module
            orphanRemoval: false
    lifecycleCallbacks: {  }
