Souscategorie:
    type: entity
    table: souscategorie
    indexes:
        fk_SousCategorie_Categorie1_idx:
            columns:
                - categorie_id
    id:
        idSousCategorie:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: id_sous_categorie
            generator:
                strategy: IDENTITY
    fields:
        nom:
            type: string
            nullable: false
            length: 45
            fixed: false
            comment: ''
    manyToOne:
        categorie:
            targetEntity: Categorie
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                categorie_id:
                    referencedColumnName: id_categorie
            orphanRemoval: false
    lifecycleCallbacks: {  }
