#------------ debut Statique
odysseus_front_plan:
    path:     /plan-du-site
    defaults: { _controller: OdysseusFrontBundle:Statique:planSite }

odysseus_front_contact:   
    path:     /contact
    defaults: { _controller: OdysseusFrontBundle:Statique:contact }

odysseus_front_cgv:    
    path:     /conditions-de-vente/{id}
    defaults: { _controller: OdysseusFrontBundle:Statique:page }

odysseus_front_mentions:    
    path:     /mentions-legales/{id}
    defaults: { _controller: OdysseusFrontBundle:Statique:page } 
#------------ fin Statique

#------------ debut Main
odysseus_front_home:
    path:     /home
    defaults: { _controller: OdysseusFrontBundle:Main:home }
 #------------ fin Main  
 
 #------------ debut Panier
odysseus_front_panier:    
    path:     /panier
    defaults: { _controller: OdysseusFrontBundle:Panier:panier }
    
odysseus_front_livraison:    
    path:     /panier/livraison
    defaults: { _controller: OdysseusFrontBundle:Panier:livraison }

odysseus_front_frais:    
    path:     /panier/frais
    defaults: { _controller: OdysseusFrontBundle:Panier:frais }
    
odysseus_front_payer:    
    path:     /panier/payer
    defaults: { _controller: OdysseusFrontBundle:Panier:payer }  
#------------ fin Panier


#------------ debut Client
odysseus_front_connexion:
    path:     /connexion
    defaults: { _controller: OdysseusFrontBundle:Client:connexion }
#------------ fin Client


#------------ debut ProduitVente
odysseus_front_categorieProduit:
    path:     /categorie/{categorie}
    defaults: { _controller: OdysseusFrontBundle:ProduitVente:categorie }
    
odysseus_front_produit_presentation:    
    path:     /produit-detail/{id}
    defaults: { _controller: OdysseusFrontBundle:ProduitVente:presentation }
    
#------------ fin Produit