#------------ debut Statique
odysseus_front_plan:
    path:     /plan-du-site
    defaults: { _controller: OdysseusFrontBundle:Statique:planSite }

odysseus_front_contact:   
    path:     /contact
    defaults: { _controller: OdysseusFrontBundle:Statique:contact }

odysseus_front_cgv:    
    path:     /conditions-de-vente
    defaults: { _controller: OdysseusFrontBundle:Statique:conditionsVentes }

odysseus_front_mentions:    
    path:     /mentions-legales
    defaults: { _controller: OdysseusFrontBundle:Statique:mentionsLegales }
    
#------------ fin Statique
#------------ debut Main
odysseus_front_home:
    path:     /home
    defaults: { _controller: OdysseusFrontBundle:Main:home }
    
#odysseus_front_produit:    
    #path:     /produit
    #defaults: { _controller: OdysseusFrontBundle:Main:produit }
    
odysseus_front_panier:    
    path:     /panier
    defaults: { _controller: OdysseusFrontBundle:Main:panier }

    
#------------ fin Main
#------------ debut Client
odysseus_front_connexion:
    path:     /connexion
    defaults: { _controller: OdysseusFrontBundle:Client:connexion }
#------------ fin Client
#------------ debut FOSUser route
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile
#------------ fin 