services:
    rs_user.registration_complet:
        class: Odysseus\FrontBundle\EventListener\RegistrationConfirmListener
        arguments: [@router]
        tags:
            - { name: kernel.event_subscriber }
            
    odysseus.registration.form.type:
        class: Odysseus\FrontBundle\Form\Type\RegistrationFormType
        tags:
            - { name: form.type, alias: odysseus_user_registration }