#------------ debut FOSUser route
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile
#------------ fin

odysseus_front_home:
    path:     /home
    defaults: { _controller: OdysseusFrontBundle:Main:home }
    
odysseus_back_home:
    path:     /
    defaults: { _controller: OdysseusBackBundle:Back:index }

#-------------- Profile
odysseus_front_profile_edit:
    path:     /profile/edit
    defaults: { _controller: OdysseusUserBundle:Profile:edit }

odysseus_front_profile_view:
    path:     /profile
    defaults: { _controller: OdysseusUserBundle:Profile:show }

#-------------- fin

#-------------- Profile Adresse
odysseus_front_profile_adresse:
    path:     /profile/adresse
    defaults: { _controller: OdysseusUserBundle:Profile:adresse }

odysseus_front_adresse_ajout:
    path:     /profile/adresse/ajout
    defaults: { _controller: OdysseusUserBundle:Profile:adresseAjout }

odysseus_front_adresse_edit:
    path:     /profile/adresse/edit/{id}
    defaults: { _controller: OdysseusUserBundle:Profile:adresseEdit }

odysseus_front_adresse_supp:
    path:     /profile/adresse/supression/{id}
    defaults: { _controller: OdysseusUserBundle:Profile:adresseSuppression }
#-------------- fin

#-------------- Profile article
odysseus_front_profile_article:
    path:     /profile/produit
    defaults: { _controller: OdysseusUserBundle:Profile:article }

odysseus_front_profile_article_ajout:
    path:     /profile/produit/ajouter
    defaults: { _controller: OdysseusUserBundle:Profile:ajouterArticle }

odysseus_front_profile_article_ajout_info:
    path:     /profile/article/ajouter/{id}
    defaults: { _controller: OdysseusUserBundle:ArticleProfile:ajouterArticleInfo }