Odysseus\FrontBundle\Entity\Administrateur:
    type: entity
    table: administrateur
    id:
        idAdministrateur:
            type: integer
            nullable: false
            unsigned: false
            id: true
            column: id_administrateur
            generator:
                strategy: IDENTITY
    fields:
        prenom:
            type: string
            nullable: false
            length: 45
            fixed: false
        nom:
            type: string
            nullable: false
            length: 45
            fixed: false
        email:
            type: string
            nullable: false
            length: 45
            fixed: false
        estSuperAdmin:
            type: boolean
            nullable: false
            column: est_super_admin
        mdp:
            type: string
            nullable: true
            length: 32
            fixed: false
    lifecycleCallbacks: {  }
