Odysseus\FrontBundle\Entity\Adresse:
    type: entity
    table: adresse
    indexes:
        fk_Adresse_Etat1_idx:
            columns:
                - etat_id
    id:
        idAdresse:
            type: integer
            nullable: false
            unsigned: false
            id: true
            column: id_adresse
            generator:
                strategy: IDENTITY
    fields:
        type:
            type: boolean
            nullable: false
        adresse:
            type: string
            nullable: false
            length: 255
            fixed: false
        cp:
            type: integer
            nullable: false
            unsigned: false
        ville:
            type: string
            nullable: false
            length: 60
            fixed: false
        pays:
            type: string
            nullable: false
            length: 45
            fixed: false
    manyToOne:
        etat:
            targetEntity: Etat
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                etat_id:
                    referencedColumnName: id_etat
            orphanRemoval: false
    lifecycleCallbacks: {  }
