Odysseus\FrontBundle\Entity\Categorie:
    type: entity
    table: categorie
    id:
        idCategorie:
            type: integer
            nullable: false
            unsigned: false
            id: true
            column: id_categorie
            generator:
                strategy: IDENTITY
    fields:
        nom:
            type: string
            nullable: false
            length: 45
            fixed: false
        alaune:
            type: boolean
            nullable: false
    manyToMany:
        attributProduitAttributProduit:
            targetEntity: Attributproduit
            cascade: {  }
            mappedBy: null
            inversedBy: categorieCategorie
            joinTable:
                name: categorie_has_attributproduit
                joinColumns:
                    -
                        name: categorie_id_categorie
                        referencedColumnName: id_categorie
                inverseJoinColumns:
                    -
                        name: attribut_produit_id_attribut_produit
                        referencedColumnName: id_attribut_produit
            orderBy: null
    lifecycleCallbacks: {  }
