Odysseus\FrontBundle\Entity\Client:
    type:  entity
    table: client
    id:
        id:
            column: id_client
            type: integer
            generator:
                strategy: AUTO