Odysseus\FrontBundle\Entity\Client:
    type: entity
    table: client
    repositoryClass: Odysseus\FrontBundle\Repository\ClientRepository
    indexes:
        fk_Client_Etat1_idx:
            columns:
                - etat_id
        fk_Client_User_idx:
            columns:
                - user_id
        fk_Client_Adresse1_idx:
            columns:
                - adresse_id
    id:
        id_client:
            type: integer
            nullable: false
            unsigned: false
            id: true
            column: id_client
            generator:
                strategy: IDENTITY
    fields:
        civilite:
            type: string
            nullable: false
            columnDefinition: ENUM('M.', 'Mme')
            length: 45
            fixed: false
        prenom:
            type: string
            nullable: false
            length: 45
            fixed: false
        nom:
            type: string
            nullable: false
            length: 45
            fixed: false
        newsletter:
            type: boolean
            nullable: false
        premium:
            type: boolean
            nullable: false
        telephone:
            type: string
            nullable: true
            length: 45
            fixed: false
        dateNaissance:
            type: datetime
            nullable: false
            column: date_naissance
        dateCreation:
            type: datetime
            nullable: false
            column: date_creation
        dateModification:
            type: datetime
            nullable: true
            column: date_modification
    manyToOne:
        etat:
            targetEntity: Etat
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                etat_id:
                    referencedColumnName: id_etat
            orphanRemoval: false
        adresse:
            targetEntity: Adresse
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                adresse_id:
                    referencedColumnName: id_adresse
            orphanRemoval: false
    oneToOne:
        user:
            targetEntity: Odysseus\UserBundle\Entity\User
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumn:
              name: user_id
              referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
