Odysseus\FrontBundle\Entity\Commande:
    type: entity
    table: commande
    indexes:
        fk_Commande_modePaiement1_idx:
            columns:
                - mode_paiement_id
        fk_Commande_etat1_idx:
            columns:
                - etat_id
        fk_Commande_Client1_idx:
            columns:
                - client_id_client
    id:
        idCommande:
            type: integer
            nullable: false
            unsigned: false
            id: true
            column: id_commande
            generator:
                strategy: IDENTITY
    fields:
        clientIp:
            type: string
            nullable: false
            length: 45
            fixed: false
            column: client_ip
        dateCommande:
            type: datetime
            nullable: false
            column: date_commande
        datePaiement:
            type: datetime
            nullable: false
            column: date_paiement
        montant:
            type: integer
            nullable: false
            unsigned: false
        adresseLivraisonId:
            type: integer
            nullable: false
            unsigned: false
            column: adresse_livraison_id
        adresseFacturationId:
            type: integer
            nullable: true
            unsigned: false
            column: adresse_facturation_id
    manyToOne:
        modePaiement:
            targetEntity: Modepaiement
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                mode_paiement_id:
                    referencedColumnName: id_mode_paiement
            orphanRemoval: false
        etat:
            targetEntity: Etat
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                etat_id:
                    referencedColumnName: id_etat
            orphanRemoval: false
        clientClient:
            targetEntity: Client
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                client_id_client:
                    referencedColumnName: id_client
            orphanRemoval: false
    manyToMany:
        produitVenteproduitVente:
            targetEntity: ProduitVente
            cascade: {  }
            mappedBy: null
            inversedBy: commandeCommande
            joinTable:
                name: commande_has_produit_vente
                joinColumns:
                    -
                        name: Commande_id_commande
                        referencedColumnName: id_commande
                inverseJoinColumns:
                    -
                        name: Produit_Vente_idProduit_Vente
                        referencedColumnName: idProduit_Vente
            orderBy: null
    lifecycleCallbacks: {  }
