Odysseus\FrontBundle\Entity\Commentaireclient:
    type: entity
    table: commentaireclient
    indexes:
        fk_CommentaireProduit_Client1_idx:
            columns:
                - acheteur_client_id
        fk_CommentaireClient_Client1_idx:
            columns:
                - vendeur_client_id
    id:
        idCommentaireClient:
            type: integer
            nullable: false
            unsigned: false
            id: true
            column: id_commentaire_client
            generator:
                strategy: IDENTITY
    fields:
        texte:
            type: text
            nullable: false
            length: 65535
            fixed: false
        note:
            type: float
            nullable: false
            precision: 10
            scale: 0
        dateCreation:
            type: datetime
            nullable: false
            column: date_creation
        dateModification:
            type: datetime
            nullable: false
            column: date_modification
    manyToOne:
        acheteurClient:
            targetEntity: Client
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                acheteur_client_id:
                    referencedColumnName: id_client
            orphanRemoval: false
        vendeurClient:
            targetEntity: Client
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                vendeur_client_id:
                    referencedColumnName: id_client
            orphanRemoval: false
    lifecycleCallbacks: {  }
