Odysseus\FrontBundle\Entity\Commentaireclient:
    type: entity
    table: commentaireclient
    indexes:
        fk_CommentaireClient_User1_idx:
            columns:
                - acheteur_user_id
        fk_CommentaireClient_User1_idx:
            columns:
                - vendeur_user_id
    id:
        idCommentaireClient:
            type: integer
            nullable: false
            unsigned: false
            id: true
            column: id_commentaire_client
            generator:
                strategy: IDENTITY
    fields:
        texte:
            type: text
            nullable: false
            length: 65535
            fixed: false
        note:
            type: float
            nullable: false
            precision: 10
            scale: 0
        dateCreation:
            type: datetime
            nullable: false
            column: date_creation
        dateModification:
            type: datetime
            nullable: false
            column: date_modification
    manyToOne:
        acheteurUser:
            targetEntity: Odysseus\UserBundle\Entity\User
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                acheteur_user_id:
                    referencedColumnName: id
            orphanRemoval: false
        vendeurUser:
            targetEntity: Odysseus\UserBundle\Entity\User
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                vendeur_user_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
