Odysseus\FrontBundle\Entity\Image:
    type: entity
    table: image
    indexes:
        fk_Image_ProduitVente1_idx:
            columns:
                - produit_vente_id

    id:
        idImage:
            type: integer
            nullable: false
            unsigned: false
            id: true
            column: id_image
            generator:
                strategy: IDENTITY
    fields:
        extension:
            type: string
            length: 255
            nullable: false
        alt:
            type: string
            nullable: false
            length: 255
        file:
            type: string
            length: 255
            nullable: false

        tempFileName:
            type: string
            length: 255
            nullable: false      
    manyToOne:
        produitVente:
            targetEntity: ProduitVente
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                produit_vente_id:
                    referencedColumnName: id_produit_vente
            orphanRemoval: false 
    lifecycleCallbacks: {  }

