Odysseus\FrontBundle\Entity\Pagestatique:
    type: entity
    table: pagestatique
    id:
        idPageStatique:
            type: integer
            nullable: false
            unsigned: false
            id: true
            column: id_page_statique
            generator:
                strategy: IDENTITY
    fields:
        titre:
            type: string
            length: 255
        contenu:
            type: text
        slug:
            type: string
            length: 255
    lifecycleCallbacks: {  }
