Odysseus\FrontBundle\Entity\ProduitVente:
    type: entity
    table: produit_vente
    indexes:
        fk_Produit_Vente_Produit1_idx:
            columns:
                - produit_id
        fk_Produit_Vente_Client1_idx:
            columns:
                - client_id
    id:
        idproduitVente:
            type: integer
            nullable: false
            unsigned: false
            id: true
            column: idProduit_Vente
            generator:
                strategy: IDENTITY
    fields:
        stock:
            type: integer
            nullable: false
            unsigned: false
    manyToOne:
        produit:
            targetEntity: Produit
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                produit_id:
                    referencedColumnName: id_produit
            orphanRemoval: false
        client:
            targetEntity: Client
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                client_id:
                    referencedColumnName: id_client
            orphanRemoval: false
    manyToMany:
        commandeCommande:
            targetEntity: Commande
            cascade: {  }
            mappedBy: produitVenteproduitVente
            inversedBy: null
            joinTable: null
            orderBy: null
    lifecycleCallbacks: {  }
