Odysseus\FrontBundle\Entity\ProduitVente:
    type: entity
    table: produit_vente
    repositoryClass: Odysseus\FrontBundle\Repository\ProduitVenteRepository
    indexes:
        fk_Produit_Vente_Produit1_idx:
            columns:
                - produit_id
        fk_Produit_Vente_User1_idx:
            columns:
                - user_id
    id:
        idProduitVente:
            type: integer
            nullable: false
            unsigned: false
            id: true
            column: id_produit_vente
            generator:
                strategy: IDENTITY
    fields:
        stock:
            type: integer
            nullable: false
            unsigned: false
        remarque:
            type: text
            length: 255
            nullable: true
        prix:
            type: float
            nullable: false
            unsigned: false
        dateAjout:
            type: datetime
            nullable: false
            unsigned: false
            column: date_ajout
    manyToOne:
        produit:
            targetEntity: Produit
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                produit_id:
                    referencedColumnName: id_produit
            orphanRemoval: false
        user:
            targetEntity: Odysseus\UserBundle\Entity\User
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                user_id:
                    referencedColumnName: id
            orphanRemoval: false
        etat:
            targetEntity: Etat
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                etat_id:
                    referencedColumnName: id_etat
            orphanRemoval: false
    manyToMany:
        commandeCommande:
            targetEntity: Commande
            cascade: {  }
            mappedBy: produitVenteproduitVente
            inversedBy: null
            joinTable: null
            orderBy: null
    lifecycleCallbacks: {  }
